### ISSUE TITLE
Release checkpoints on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [Hanbo-Cheng/DAWN-pytorch#1]
Hi @Hanbo-Cheng,

Niels here from the open-source team at Hugging Face. I discovered your work through AK's daily papers: https://huggingface.co/papers/2410.13726. The paper page lets people discuss the paper, and discover its artifacts (such as your models, dataset, a demo in the form of a 🤗 Space).

It'd be great to make the checkpoints available on the 🤗 hub, to improve their discoverability/visibility.
We can add tags so that people find them when filtering https://huggingface.co/models.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. 

In this case, we could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to any custom `nn.Module`. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. We can then also link the checkpoints to the paper page.

Let me know if you're interested/need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by Hanbo-Cheng** [comment]
Thank you for your attention and suggestions! We initially planned to provide checkpoints via Google Drive, but your suggestion sounds like a good option, so we will consider uploading our checkpoints on HF.

**Comment by Hanbo-Cheng** [comment]
Thank you for your attention and suggestions! We initially planned to provide checkpoints via Google Drive, but your suggestion sounds like a good option, so we will consider uploading our checkpoints on HF.

**Comment by NielsRogge** [comment]
That's great, yes we know researchers publish a lot of their artifacts on Google Drive currently, it's something we'd like to change 😅  as it might improve the discoverability/accessibility of your work

**Comment by Hanbo-Cheng** [comment]
We have uploaded our pretrained model on [Hugging Face](https://huggingface.co/Hanbo-Cheng/DAWN). This is indeed an excellent way to release models, as in the past, I often worried about the issue of cloud drive links becoming inactive. Thank you again for your advice; in future open-source work, I will use Hugging Face more frequently to share my models! :smile:

**Comment by gdamms** [comment]
Hello there, the link seems to be dead now, it returns a 404. Did you made it private or migrated it?

**Comment by Hanbo-Cheng** [comment]
@gdamms  Sorry for the late reply. I have been too busy recently and haven't checked messages. Thank you for the reminder, it has been addressed now.
