### ISSUE TITLE
How to process long audio

### ISSUE THREAD

**Issue by nitinmukesh** [Hanbo-Cheng/DAWN-pytorch#11]
It defaults to 8s /25fps audio output.
I want to process 20s output. Where should I make the change?

**Comment by Hanbo-Cheng** [comment]
changing `MAX_N_FRAMES` in `DM_3\test_demo\test_VIDEO_hdtf_df_wpose_face_cond_init_ca_newae_ood_256_2.py` will help.

**Comment by nitinmukesh** [comment]
Thank you.
