### ISSUE TITLE
link of models on huggingface seem to be invalid

### ISSUE THREAD

**Issue by BlueSkyyyyyy** [Hanbo-Cheng/DAWN-pytorch#14]
https://huggingface.co/Hanbo-Cheng/DAWN  can't find the page

**Comment by tszssong** [comment]
mark

**Comment by SQYmu** [comment]
mark

**Comment by jiten634** [comment]
same issue

**Comment by magebase-dev** [comment]
same issue

**Comment by Hanbo-Cheng** [comment]
Sorry for the late reply. I have been too busy recently and haven't checked messages. Thank you for the reminder, it has been addressed now.
