### ISSUE TITLE
Demo looks awesome. Any planned date for code and checkpoint release

### ISSUE THREAD

**Issue by nitinmukesh** [Hanbo-Cheng/DAWN-pytorch#2]
As title says

**Comment by Hanbo-Cheng** [comment]
Thank you for your attention! We plan to release the inference code and checkpoint by December. We are currently preparing the code.

**Comment by Hanbo-Cheng** [comment]
Hello, we have released the pretrained model and code for inference. We welcome you to try it out! :smile:
