### ISSUE TITLE
Missing optimized code

### ISSUE THREAD

**Issue by nitinmukesh** [Hanbo-Cheng/DAWN-pytorch#6]
Both links not working in Readme

> PS: Although optimized [code](https://github.com/Hanbo-Cheng/DAWN-pytorch/blob/main/DM_3%5Cmodules%5Cvideo_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test_local_opt.py) can improve VRAM utilization, it currently sacrifices inference speed due to incomplete optimization of local attention. We are actively working on this issue, and if you have a better solution, we welcome your PR. If you wish to achieve faster inference speeds, you can use [unoptimized code](https://github.com/Hanbo-Cheng/DAWN-pytorch/blob/main/DM_3%5Cmodules%5Cvideo_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py), but this will increase VRAM usage (O(n²) spatial complexity).

**Comment by Hanbo-Cheng** [comment]
Thank you for pointing out the issue. This is because the path separator in the Windows system is "\" which does not comply with GitHub's path indexing rules. It has been fixed now.
